server:
  port: 8082

spring:
  profiles:
    active: dev

ice:
  app: 1
  rmi:
    port: 8210
    communicatePort: 18210
    server: 127.0.0.1:8212
  pool:
    coreSize: 4
    maxSize: 4
    keepAliveSeconds: 60
    queueCapacity: 60000
test:
  value: 123
environment: dev



