server:
  port: 8082

spring:
  profiles:
    active: dev

ice:
  app: 1
  rabbit:
    port: 5672
    host: localhost
    username: guest
    password: guest
    reply-timeout: 10000
  pool:
    coreSize: 4
    maxSize: 4
    keepAliveSeconds: 10
    queueCapacity: 60000
test:
  value: 123
environment: dev



