server:
  port: 8082

spring:
  profiles:
    active: dev

ice:
  app: 1
  rmi:
    port: 9099
    server: 127.0.0.1:8088
  pool:
    coreSize: 4
    maxSize: 4
    keepAliveSeconds: 10
    queueCapacity: 60000
test:
  value: 123
environment: dev



