server:
  port: 8121
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ice?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: zjn
    password: zjnzjn
ice:
  rmi:
    port: 8212
    communicatePort: 18212
environment: dev