server:
  port: 8121
spring:
  rabbitmq:
    port: 5672
    host: 127.0.0.1
    username: admin
    password: admin
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ice?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: zjn
    password: zjn
environment: dev